//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for auditTrailWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="auditTrailWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdAuditDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createdTmStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="createdUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hippaSegmentMappingVO" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentMappingWebServiceVO" minOccurs="0"/>
 *         &lt;element name="mappingStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ruleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spsId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="systemComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableAuditStatus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="variableDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "auditTrailWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "createdAuditDate",
    "createdTmStamp",
    "createdUser",
    "hippaSegmentMappingVO",
    "mappingStatus",
    "ruleId",
    "spsId",
    "systemComments",
    "userComments",
    "variableAuditStatus",
    "variableDesc",
    "variableId"
})
public class AuditTrailWebServiceVO {

    protected String createdAuditDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdTmStamp;
    protected String createdUser;
    protected HippaSegmentMappingWebServiceVO hippaSegmentMappingVO;
    protected String mappingStatus;
    protected String ruleId;
    protected String spsId;
    protected String systemComments;
    protected String userComments;
    protected Integer variableAuditStatus;
    protected String variableDesc;
    protected String variableId;

    /**
     * Gets the value of the createdAuditDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedAuditDate() {
        return createdAuditDate;
    }

    /**
     * Sets the value of the createdAuditDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedAuditDate(String value) {
        this.createdAuditDate = value;
    }

    /**
     * Gets the value of the createdTmStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedTmStamp() {
        return createdTmStamp;
    }

    /**
     * Sets the value of the createdTmStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedTmStamp(XMLGregorianCalendar value) {
        this.createdTmStamp = value;
    }

    /**
     * Gets the value of the createdUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * Sets the value of the createdUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedUser(String value) {
        this.createdUser = value;
    }

    /**
     * Gets the value of the hippaSegmentMappingVO property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentMappingWebServiceVO }
     *     
     */
    public HippaSegmentMappingWebServiceVO getHippaSegmentMappingVO() {
        return hippaSegmentMappingVO;
    }

    /**
     * Sets the value of the hippaSegmentMappingVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentMappingWebServiceVO }
     *     
     */
    public void setHippaSegmentMappingVO(HippaSegmentMappingWebServiceVO value) {
        this.hippaSegmentMappingVO = value;
    }

    /**
     * Gets the value of the mappingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappingStatus() {
        return mappingStatus;
    }

    /**
     * Sets the value of the mappingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappingStatus(String value) {
        this.mappingStatus = value;
    }

    /**
     * Gets the value of the ruleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * Sets the value of the ruleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleId(String value) {
        this.ruleId = value;
    }

    /**
     * Gets the value of the spsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpsId() {
        return spsId;
    }

    /**
     * Sets the value of the spsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpsId(String value) {
        this.spsId = value;
    }

    /**
     * Gets the value of the systemComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemComments() {
        return systemComments;
    }

    /**
     * Sets the value of the systemComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemComments(String value) {
        this.systemComments = value;
    }

    /**
     * Gets the value of the userComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserComments() {
        return userComments;
    }

    /**
     * Sets the value of the userComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserComments(String value) {
        this.userComments = value;
    }

    /**
     * Gets the value of the variableAuditStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVariableAuditStatus() {
        return variableAuditStatus;
    }

    /**
     * Sets the value of the variableAuditStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVariableAuditStatus(Integer value) {
        this.variableAuditStatus = value;
    }

    /**
     * Gets the value of the variableDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableDesc() {
        return variableDesc;
    }

    /**
     * Sets the value of the variableDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableDesc(String value) {
        this.variableDesc = value;
    }

    /**
     * Gets the value of the variableId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableId() {
        return variableId;
    }

    /**
     * Sets the value of the variableId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableId(String value) {
        this.variableId = value;
    }

}
