//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contractMappingWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contractMappingWebServiceVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}mappingWebServiceVO">
 *       &lt;sequence>
 *         &lt;element name="benefitEffectiveEndDate" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="benefitEffectiveStartDate" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="eb04" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="eb05" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="eb07" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="eb08" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="eb10" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="eb11" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="eb12" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaSegmentWebServiceVO" minOccurs="0"/>
 *         &lt;element name="errorCodesList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorDetailWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="iiiMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tierDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contractMappingWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "benefitEffectiveEndDate",
    "benefitEffectiveStartDate",
    "eb04",
    "eb05",
    "eb07",
    "eb08",
    "eb10",
    "eb11",
    "eb12",
    "errorCodesList",
    "iiiMessage",
    "tierDescription"
})
public class ContractMappingWebServiceVO
    extends MappingWebServiceVO
{

    protected HippaSegmentWebServiceVO benefitEffectiveEndDate;
    protected HippaSegmentWebServiceVO benefitEffectiveStartDate;
    protected HippaSegmentWebServiceVO eb04;
    protected HippaSegmentWebServiceVO eb05;
    protected HippaSegmentWebServiceVO eb07;
    protected HippaSegmentWebServiceVO eb08;
    protected HippaSegmentWebServiceVO eb10;
    protected HippaSegmentWebServiceVO eb11;
    protected HippaSegmentWebServiceVO eb12;
    @XmlElement(nillable = true)
    protected List<ErrorDetailWebServiceVO> errorCodesList;
    protected String iiiMessage;
    protected String tierDescription;

    /**
     * Gets the value of the benefitEffectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getBenefitEffectiveEndDate() {
        return benefitEffectiveEndDate;
    }

    /**
     * Sets the value of the benefitEffectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setBenefitEffectiveEndDate(HippaSegmentWebServiceVO value) {
        this.benefitEffectiveEndDate = value;
    }

    /**
     * Gets the value of the benefitEffectiveStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getBenefitEffectiveStartDate() {
        return benefitEffectiveStartDate;
    }

    /**
     * Sets the value of the benefitEffectiveStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setBenefitEffectiveStartDate(HippaSegmentWebServiceVO value) {
        this.benefitEffectiveStartDate = value;
    }

    /**
     * Gets the value of the eb04 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getEb04() {
        return eb04;
    }

    /**
     * Sets the value of the eb04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setEb04(HippaSegmentWebServiceVO value) {
        this.eb04 = value;
    }

    /**
     * Gets the value of the eb05 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getEb05() {
        return eb05;
    }

    /**
     * Sets the value of the eb05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setEb05(HippaSegmentWebServiceVO value) {
        this.eb05 = value;
    }

    /**
     * Gets the value of the eb07 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getEb07() {
        return eb07;
    }

    /**
     * Sets the value of the eb07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setEb07(HippaSegmentWebServiceVO value) {
        this.eb07 = value;
    }

    /**
     * Gets the value of the eb08 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getEb08() {
        return eb08;
    }

    /**
     * Sets the value of the eb08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setEb08(HippaSegmentWebServiceVO value) {
        this.eb08 = value;
    }

    /**
     * Gets the value of the eb10 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getEb10() {
        return eb10;
    }

    /**
     * Sets the value of the eb10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setEb10(HippaSegmentWebServiceVO value) {
        this.eb10 = value;
    }

    /**
     * Gets the value of the eb11 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getEb11() {
        return eb11;
    }

    /**
     * Sets the value of the eb11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setEb11(HippaSegmentWebServiceVO value) {
        this.eb11 = value;
    }

    /**
     * Gets the value of the eb12 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public HippaSegmentWebServiceVO getEb12() {
        return eb12;
    }

    /**
     * Sets the value of the eb12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaSegmentWebServiceVO }
     *     
     */
    public void setEb12(HippaSegmentWebServiceVO value) {
        this.eb12 = value;
    }

    /**
     * Gets the value of the errorCodesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorCodesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorCodesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorDetailWebServiceVO }
     * 
     * 
     */
    public List<ErrorDetailWebServiceVO> getErrorCodesList() {
        if (errorCodesList == null) {
            errorCodesList = new ArrayList<ErrorDetailWebServiceVO>();
        }
        return this.errorCodesList;
    }

    /**
     * Gets the value of the iiiMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIiiMessage() {
        return iiiMessage;
    }

    /**
     * Sets the value of the iiiMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIiiMessage(String value) {
        this.iiiMessage = value;
    }

    /**
     * Gets the value of the tierDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTierDescription() {
        return tierDescription;
    }

    /**
     * Sets the value of the tierDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTierDescription(String value) {
        this.tierDescription = value;
    }

}
