//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contractWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contractWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="backEndRegion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="businessEntity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contractMappingVOList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}contractMappingWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorCodesList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorDetailWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="errorExclusionDetailList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorExclusionWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="errorExclusionDetailVO" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorExclusionDetailWebServiceVO" minOccurs="0"/>
 *         &lt;element name="errorExclusionList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorExclusionWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="groupStateHQ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="majorHeadings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="value" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}majorHeadingsWebServiceVO" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="system" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contractWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "backEndRegion",
    "businessEntity",
    "contractId",
    "contractMappingVOList",
    "effectiveDate",
    "errorCodesList",
    "errorExclusionDetailList",
    "errorExclusionDetailVO",
    "errorExclusionList",
    "expiryDate",
    "groupStateHQ",
    "majorHeadings",
    "system",
    "version"
})
public class ContractWebServiceVO {

    protected String backEndRegion;
    protected String businessEntity;
    protected String contractId;
    @XmlElement(nillable = true)
    protected List<ContractMappingWebServiceVO> contractMappingVOList;
    protected String effectiveDate;
    @XmlElement(nillable = true)
    protected List<ErrorDetailWebServiceVO> errorCodesList;
    @XmlElement(nillable = true)
    protected List<ErrorExclusionWebServiceVO> errorExclusionDetailList;
    protected ErrorExclusionDetailWebServiceVO errorExclusionDetailVO;
    @XmlElement(nillable = true)
    protected List<ErrorExclusionWebServiceVO> errorExclusionList;
    protected String expiryDate;
    protected String groupStateHQ;
    @XmlElement(required = true)
    protected ContractWebServiceVO.MajorHeadings majorHeadings;
    protected String system;
    protected int version;

    /**
     * Gets the value of the backEndRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackEndRegion() {
        return backEndRegion;
    }

    /**
     * Sets the value of the backEndRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackEndRegion(String value) {
        this.backEndRegion = value;
    }

    /**
     * Gets the value of the businessEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntity() {
        return businessEntity;
    }

    /**
     * Sets the value of the businessEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntity(String value) {
        this.businessEntity = value;
    }

    /**
     * Gets the value of the contractId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * Sets the value of the contractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractId(String value) {
        this.contractId = value;
    }

    /**
     * Gets the value of the contractMappingVOList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contractMappingVOList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContractMappingVOList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContractMappingWebServiceVO }
     * 
     * 
     */
    public List<ContractMappingWebServiceVO> getContractMappingVOList() {
        if (contractMappingVOList == null) {
            contractMappingVOList = new ArrayList<ContractMappingWebServiceVO>();
        }
        return this.contractMappingVOList;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the errorCodesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorCodesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorCodesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorDetailWebServiceVO }
     * 
     * 
     */
    public List<ErrorDetailWebServiceVO> getErrorCodesList() {
        if (errorCodesList == null) {
            errorCodesList = new ArrayList<ErrorDetailWebServiceVO>();
        }
        return this.errorCodesList;
    }

    /**
     * Gets the value of the errorExclusionDetailList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorExclusionDetailList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorExclusionDetailList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorExclusionWebServiceVO }
     * 
     * 
     */
    public List<ErrorExclusionWebServiceVO> getErrorExclusionDetailList() {
        if (errorExclusionDetailList == null) {
            errorExclusionDetailList = new ArrayList<ErrorExclusionWebServiceVO>();
        }
        return this.errorExclusionDetailList;
    }

    /**
     * Gets the value of the errorExclusionDetailVO property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorExclusionDetailWebServiceVO }
     *     
     */
    public ErrorExclusionDetailWebServiceVO getErrorExclusionDetailVO() {
        return errorExclusionDetailVO;
    }

    /**
     * Sets the value of the errorExclusionDetailVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorExclusionDetailWebServiceVO }
     *     
     */
    public void setErrorExclusionDetailVO(ErrorExclusionDetailWebServiceVO value) {
        this.errorExclusionDetailVO = value;
    }

    /**
     * Gets the value of the errorExclusionList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorExclusionList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorExclusionList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorExclusionWebServiceVO }
     * 
     * 
     */
    public List<ErrorExclusionWebServiceVO> getErrorExclusionList() {
        if (errorExclusionList == null) {
            errorExclusionList = new ArrayList<ErrorExclusionWebServiceVO>();
        }
        return this.errorExclusionList;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the groupStateHQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupStateHQ() {
        return groupStateHQ;
    }

    /**
     * Sets the value of the groupStateHQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupStateHQ(String value) {
        this.groupStateHQ = value;
    }

    /**
     * Gets the value of the majorHeadings property.
     * 
     * @return
     *     possible object is
     *     {@link ContractWebServiceVO.MajorHeadings }
     *     
     */
    public ContractWebServiceVO.MajorHeadings getMajorHeadings() {
        return majorHeadings;
    }

    /**
     * Sets the value of the majorHeadings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractWebServiceVO.MajorHeadings }
     *     
     */
    public void setMajorHeadings(ContractWebServiceVO.MajorHeadings value) {
        this.majorHeadings = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystem(String value) {
        this.system = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="value" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}majorHeadingsWebServiceVO" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class MajorHeadings {

        protected List<ContractWebServiceVO.MajorHeadings.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ContractWebServiceVO.MajorHeadings.Entry }
         * 
         * 
         */
        public List<ContractWebServiceVO.MajorHeadings.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<ContractWebServiceVO.MajorHeadings.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="value" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}majorHeadingsWebServiceVO" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry {

            protected String key;
            protected MajorHeadingsWebServiceVO value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link MajorHeadingsWebServiceVO }
             *     
             */
            public MajorHeadingsWebServiceVO getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link MajorHeadingsWebServiceVO }
             *     
             */
            public void setValue(MajorHeadingsWebServiceVO value) {
                this.value = value;
            }

        }

    }

}
