//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eb03AssociationWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eb03AssociationWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eb03" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaCodeValueWebServiceVO" minOccurs="0"/>
 *         &lt;element name="noteType" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaCodeValueWebServiceVO" minOccurs="0"/>
 *         &lt;element name="iii02List" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaCodeValueWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="msgReqdInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eb03String" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seq_num" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eb03AssociationWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "eb03",
    "noteType",
    "iii02List",
    "message",
    "msgReqdInd",
    "eb03String",
    "seqNum"
})
public class Eb03AssociationWebServiceVO {

    protected HippaCodeValueWebServiceVO eb03;
    protected HippaCodeValueWebServiceVO noteType;
    @XmlElement(nillable = true)
    protected List<HippaCodeValueWebServiceVO> iii02List;
    protected String message;
    protected String msgReqdInd;
    protected String eb03String;
    @XmlElement(name = "seq_num")
    protected Long seqNum;

    /**
     * Gets the value of the eb03 property.
     * 
     * @return
     *     possible object is
     *     {@link HippaCodeValueWebServiceVO }
     *     
     */
    public HippaCodeValueWebServiceVO getEb03() {
        return eb03;
    }

    /**
     * Sets the value of the eb03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaCodeValueWebServiceVO }
     *     
     */
    public void setEb03(HippaCodeValueWebServiceVO value) {
        this.eb03 = value;
    }

    /**
     * Gets the value of the noteType property.
     * 
     * @return
     *     possible object is
     *     {@link HippaCodeValueWebServiceVO }
     *     
     */
    public HippaCodeValueWebServiceVO getNoteType() {
        return noteType;
    }

    /**
     * Sets the value of the noteType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HippaCodeValueWebServiceVO }
     *     
     */
    public void setNoteType(HippaCodeValueWebServiceVO value) {
        this.noteType = value;
    }

    /**
     * Gets the value of the iii02List property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iii02List property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIii02List().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HippaCodeValueWebServiceVO }
     * 
     * 
     */
    public List<HippaCodeValueWebServiceVO> getIii02List() {
        if (iii02List == null) {
            iii02List = new ArrayList<HippaCodeValueWebServiceVO>();
        }
        return this.iii02List;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the msgReqdInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgReqdInd() {
        return msgReqdInd;
    }

    /**
     * Sets the value of the msgReqdInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgReqdInd(String value) {
        this.msgReqdInd = value;
    }

    /**
     * Gets the value of the eb03String property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEb03String() {
        return eb03String;
    }

    /**
     * Sets the value of the eb03String property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEb03String(String value) {
        this.eb03String = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSeqNum(Long value) {
        this.seqNum = value;
    }

}
