//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

public class EbxWebSerDisplayVO {
	
	private String benefitComponent;
	private String benefit;
	private String headerRule;
	private String SPSId;
	private String PVA;
	private String format;
	private String valueCoded;
	private String messageText;
	private String noteTypeCode;
	private String error;
	private String errorDescription;
	
	public String getBenefitComponent() {
		return benefitComponent;
	}
	public void setBenefitComponent(String benefitComponent) {
		this.benefitComponent = benefitComponent;
	}
	public String getBenefit() {
		return benefit;
	}
	public void setBenefit(String benefit) {
		this.benefit = benefit;
	}
	public String getHeaderRule() {
		return headerRule;
	}
	public void setHeaderRule(String headerRule) {
		this.headerRule = headerRule;
	}
	public String getSPSId() {
		return SPSId;
	}
	public void setSPSId(String id) {
		SPSId = id;
	}
	public String getPVA() {
		return PVA;
	}
	public void setPVA(String pva) {
		PVA = pva;
	}
	public String getFormat() {
		return format;
	}
	public void setFormat(String format) {
		this.format = format;
	}
	public String getValueCoded() {
		return valueCoded;
	}
	public void setValueCoded(String valueCoded) {
		this.valueCoded = valueCoded;
	}
	public String getMessageText() {
		return messageText;
	}
	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}
	public String getNoteTypeCode() {
		return noteTypeCode;
	}
	public void setNoteTypeCode(String noteTypeCode) {
		this.noteTypeCode = noteTypeCode;
	}
	public String getError() {
		return error;
	}
	public void setError(String error) {
		this.error = error;
	}
	public String getErrorDescription() {
		return errorDescription;
	}
	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}
	
}
