//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorExclusionDetailWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="errorExclusionDetailWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contractProductLevelExclusions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="e001ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e002ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e003ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e004ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e005ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e006ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e007ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e008ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e009ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e010ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e011ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e012ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e013ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e014ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e016ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e017ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e018ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e019ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e020ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e021ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e022ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e023ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e024ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e025ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e026ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e027ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e028ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e029ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e030ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e031ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e032ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e033ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e034ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e035ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e036ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e038ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e039ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e040ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e041ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e042ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="e043ExclusionValidationEnableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="headerRuleExclusionsList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorExclusionWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="spsExclusionsList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorExclusionWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="variableExclusionsList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorExclusionWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "errorExclusionDetailWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "contractProductLevelExclusions",
    "e001ExclusionValidationEnableFlag",
    "e002ExclusionValidationEnableFlag",
    "e003ExclusionValidationEnableFlag",
    "e004ExclusionValidationEnableFlag",
    "e005ExclusionValidationEnableFlag",
    "e006ExclusionValidationEnableFlag",
    "e007ExclusionValidationEnableFlag",
    "e008ExclusionValidationEnableFlag",
    "e009ExclusionValidationEnableFlag",
    "e010ExclusionValidationEnableFlag",
    "e011ExclusionValidationEnableFlag",
    "e012ExclusionValidationEnableFlag",
    "e013ExclusionValidationEnableFlag",
    "e014ExclusionValidationEnableFlag",
    "e016ExclusionValidationEnableFlag",
    "e017ExclusionValidationEnableFlag",
    "e018ExclusionValidationEnableFlag",
    "e019ExclusionValidationEnableFlag",
    "e020ExclusionValidationEnableFlag",
    "e021ExclusionValidationEnableFlag",
    "e022ExclusionValidationEnableFlag",
    "e023ExclusionValidationEnableFlag",
    "e024ExclusionValidationEnableFlag",
    "e025ExclusionValidationEnableFlag",
    "e026ExclusionValidationEnableFlag",
    "e027ExclusionValidationEnableFlag",
    "e028ExclusionValidationEnableFlag",
    "e029ExclusionValidationEnableFlag",
    "e030ExclusionValidationEnableFlag",
    "e031ExclusionValidationEnableFlag",
    "e032ExclusionValidationEnableFlag",
    "e033ExclusionValidationEnableFlag",
    "e034ExclusionValidationEnableFlag",
    "e035ExclusionValidationEnableFlag",
    "e036ExclusionValidationEnableFlag",
    "e038ExclusionValidationEnableFlag",
    "e039ExclusionValidationEnableFlag",
    "e040ExclusionValidationEnableFlag",
    "e041ExclusionValidationEnableFlag",
    "e042ExclusionValidationEnableFlag",
    "e043ExclusionValidationEnableFlag",
    "headerRuleExclusionsList",
    "spsExclusionsList",
    "variableExclusionsList"
})
public class ErrorExclusionDetailWebServiceVO {

    @XmlElement(nillable = true)
    protected List<String> contractProductLevelExclusions;
    protected boolean e001ExclusionValidationEnableFlag;
    protected boolean e002ExclusionValidationEnableFlag;
    protected boolean e003ExclusionValidationEnableFlag;
    protected boolean e004ExclusionValidationEnableFlag;
    protected boolean e005ExclusionValidationEnableFlag;
    protected boolean e006ExclusionValidationEnableFlag;
    protected boolean e007ExclusionValidationEnableFlag;
    protected boolean e008ExclusionValidationEnableFlag;
    protected boolean e009ExclusionValidationEnableFlag;
    protected boolean e010ExclusionValidationEnableFlag;
    protected boolean e011ExclusionValidationEnableFlag;
    protected boolean e012ExclusionValidationEnableFlag;
    protected boolean e013ExclusionValidationEnableFlag;
    protected boolean e014ExclusionValidationEnableFlag;
    protected boolean e016ExclusionValidationEnableFlag;
    protected boolean e017ExclusionValidationEnableFlag;
    protected boolean e018ExclusionValidationEnableFlag;
    protected boolean e019ExclusionValidationEnableFlag;
    protected boolean e020ExclusionValidationEnableFlag;
    protected boolean e021ExclusionValidationEnableFlag;
    protected boolean e022ExclusionValidationEnableFlag;
    protected boolean e023ExclusionValidationEnableFlag;
    protected boolean e024ExclusionValidationEnableFlag;
    protected boolean e025ExclusionValidationEnableFlag;
    protected boolean e026ExclusionValidationEnableFlag;
    protected boolean e027ExclusionValidationEnableFlag;
    protected boolean e028ExclusionValidationEnableFlag;
    protected boolean e029ExclusionValidationEnableFlag;
    protected boolean e030ExclusionValidationEnableFlag;
    protected boolean e031ExclusionValidationEnableFlag;
    protected boolean e032ExclusionValidationEnableFlag;
    protected boolean e033ExclusionValidationEnableFlag;
    protected boolean e034ExclusionValidationEnableFlag;
    protected boolean e035ExclusionValidationEnableFlag;
    protected boolean e036ExclusionValidationEnableFlag;
    protected boolean e038ExclusionValidationEnableFlag;
    protected boolean e039ExclusionValidationEnableFlag;
    protected boolean e040ExclusionValidationEnableFlag;
    protected boolean e041ExclusionValidationEnableFlag;
    protected boolean e042ExclusionValidationEnableFlag;
    protected boolean e043ExclusionValidationEnableFlag;
    @XmlElement(nillable = true)
    protected List<ErrorExclusionWebServiceVO> headerRuleExclusionsList;
    @XmlElement(nillable = true)
    protected List<ErrorExclusionWebServiceVO> spsExclusionsList;
    @XmlElement(nillable = true)
    protected List<ErrorExclusionWebServiceVO> variableExclusionsList;

    /**
     * Gets the value of the contractProductLevelExclusions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contractProductLevelExclusions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContractProductLevelExclusions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContractProductLevelExclusions() {
        if (contractProductLevelExclusions == null) {
            contractProductLevelExclusions = new ArrayList<String>();
        }
        return this.contractProductLevelExclusions;
    }

    /**
     * Gets the value of the e001ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE001ExclusionValidationEnableFlag() {
        return e001ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e001ExclusionValidationEnableFlag property.
     * 
     */
    public void setE001ExclusionValidationEnableFlag(boolean value) {
        this.e001ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e002ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE002ExclusionValidationEnableFlag() {
        return e002ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e002ExclusionValidationEnableFlag property.
     * 
     */
    public void setE002ExclusionValidationEnableFlag(boolean value) {
        this.e002ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e003ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE003ExclusionValidationEnableFlag() {
        return e003ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e003ExclusionValidationEnableFlag property.
     * 
     */
    public void setE003ExclusionValidationEnableFlag(boolean value) {
        this.e003ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e004ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE004ExclusionValidationEnableFlag() {
        return e004ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e004ExclusionValidationEnableFlag property.
     * 
     */
    public void setE004ExclusionValidationEnableFlag(boolean value) {
        this.e004ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e005ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE005ExclusionValidationEnableFlag() {
        return e005ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e005ExclusionValidationEnableFlag property.
     * 
     */
    public void setE005ExclusionValidationEnableFlag(boolean value) {
        this.e005ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e006ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE006ExclusionValidationEnableFlag() {
        return e006ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e006ExclusionValidationEnableFlag property.
     * 
     */
    public void setE006ExclusionValidationEnableFlag(boolean value) {
        this.e006ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e007ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE007ExclusionValidationEnableFlag() {
        return e007ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e007ExclusionValidationEnableFlag property.
     * 
     */
    public void setE007ExclusionValidationEnableFlag(boolean value) {
        this.e007ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e008ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE008ExclusionValidationEnableFlag() {
        return e008ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e008ExclusionValidationEnableFlag property.
     * 
     */
    public void setE008ExclusionValidationEnableFlag(boolean value) {
        this.e008ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e009ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE009ExclusionValidationEnableFlag() {
        return e009ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e009ExclusionValidationEnableFlag property.
     * 
     */
    public void setE009ExclusionValidationEnableFlag(boolean value) {
        this.e009ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e010ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE010ExclusionValidationEnableFlag() {
        return e010ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e010ExclusionValidationEnableFlag property.
     * 
     */
    public void setE010ExclusionValidationEnableFlag(boolean value) {
        this.e010ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e011ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE011ExclusionValidationEnableFlag() {
        return e011ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e011ExclusionValidationEnableFlag property.
     * 
     */
    public void setE011ExclusionValidationEnableFlag(boolean value) {
        this.e011ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e012ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE012ExclusionValidationEnableFlag() {
        return e012ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e012ExclusionValidationEnableFlag property.
     * 
     */
    public void setE012ExclusionValidationEnableFlag(boolean value) {
        this.e012ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e013ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE013ExclusionValidationEnableFlag() {
        return e013ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e013ExclusionValidationEnableFlag property.
     * 
     */
    public void setE013ExclusionValidationEnableFlag(boolean value) {
        this.e013ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e014ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE014ExclusionValidationEnableFlag() {
        return e014ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e014ExclusionValidationEnableFlag property.
     * 
     */
    public void setE014ExclusionValidationEnableFlag(boolean value) {
        this.e014ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e016ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE016ExclusionValidationEnableFlag() {
        return e016ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e016ExclusionValidationEnableFlag property.
     * 
     */
    public void setE016ExclusionValidationEnableFlag(boolean value) {
        this.e016ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e017ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE017ExclusionValidationEnableFlag() {
        return e017ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e017ExclusionValidationEnableFlag property.
     * 
     */
    public void setE017ExclusionValidationEnableFlag(boolean value) {
        this.e017ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e018ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE018ExclusionValidationEnableFlag() {
        return e018ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e018ExclusionValidationEnableFlag property.
     * 
     */
    public void setE018ExclusionValidationEnableFlag(boolean value) {
        this.e018ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e019ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE019ExclusionValidationEnableFlag() {
        return e019ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e019ExclusionValidationEnableFlag property.
     * 
     */
    public void setE019ExclusionValidationEnableFlag(boolean value) {
        this.e019ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e020ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE020ExclusionValidationEnableFlag() {
        return e020ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e020ExclusionValidationEnableFlag property.
     * 
     */
    public void setE020ExclusionValidationEnableFlag(boolean value) {
        this.e020ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e021ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE021ExclusionValidationEnableFlag() {
        return e021ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e021ExclusionValidationEnableFlag property.
     * 
     */
    public void setE021ExclusionValidationEnableFlag(boolean value) {
        this.e021ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e022ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE022ExclusionValidationEnableFlag() {
        return e022ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e022ExclusionValidationEnableFlag property.
     * 
     */
    public void setE022ExclusionValidationEnableFlag(boolean value) {
        this.e022ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e023ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE023ExclusionValidationEnableFlag() {
        return e023ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e023ExclusionValidationEnableFlag property.
     * 
     */
    public void setE023ExclusionValidationEnableFlag(boolean value) {
        this.e023ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e024ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE024ExclusionValidationEnableFlag() {
        return e024ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e024ExclusionValidationEnableFlag property.
     * 
     */
    public void setE024ExclusionValidationEnableFlag(boolean value) {
        this.e024ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e025ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE025ExclusionValidationEnableFlag() {
        return e025ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e025ExclusionValidationEnableFlag property.
     * 
     */
    public void setE025ExclusionValidationEnableFlag(boolean value) {
        this.e025ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e026ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE026ExclusionValidationEnableFlag() {
        return e026ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e026ExclusionValidationEnableFlag property.
     * 
     */
    public void setE026ExclusionValidationEnableFlag(boolean value) {
        this.e026ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e027ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE027ExclusionValidationEnableFlag() {
        return e027ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e027ExclusionValidationEnableFlag property.
     * 
     */
    public void setE027ExclusionValidationEnableFlag(boolean value) {
        this.e027ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e028ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE028ExclusionValidationEnableFlag() {
        return e028ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e028ExclusionValidationEnableFlag property.
     * 
     */
    public void setE028ExclusionValidationEnableFlag(boolean value) {
        this.e028ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e029ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE029ExclusionValidationEnableFlag() {
        return e029ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e029ExclusionValidationEnableFlag property.
     * 
     */
    public void setE029ExclusionValidationEnableFlag(boolean value) {
        this.e029ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e030ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE030ExclusionValidationEnableFlag() {
        return e030ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e030ExclusionValidationEnableFlag property.
     * 
     */
    public void setE030ExclusionValidationEnableFlag(boolean value) {
        this.e030ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e031ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE031ExclusionValidationEnableFlag() {
        return e031ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e031ExclusionValidationEnableFlag property.
     * 
     */
    public void setE031ExclusionValidationEnableFlag(boolean value) {
        this.e031ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e032ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE032ExclusionValidationEnableFlag() {
        return e032ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e032ExclusionValidationEnableFlag property.
     * 
     */
    public void setE032ExclusionValidationEnableFlag(boolean value) {
        this.e032ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e033ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE033ExclusionValidationEnableFlag() {
        return e033ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e033ExclusionValidationEnableFlag property.
     * 
     */
    public void setE033ExclusionValidationEnableFlag(boolean value) {
        this.e033ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e034ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE034ExclusionValidationEnableFlag() {
        return e034ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e034ExclusionValidationEnableFlag property.
     * 
     */
    public void setE034ExclusionValidationEnableFlag(boolean value) {
        this.e034ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e035ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE035ExclusionValidationEnableFlag() {
        return e035ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e035ExclusionValidationEnableFlag property.
     * 
     */
    public void setE035ExclusionValidationEnableFlag(boolean value) {
        this.e035ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e036ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE036ExclusionValidationEnableFlag() {
        return e036ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e036ExclusionValidationEnableFlag property.
     * 
     */
    public void setE036ExclusionValidationEnableFlag(boolean value) {
        this.e036ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e038ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE038ExclusionValidationEnableFlag() {
        return e038ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e038ExclusionValidationEnableFlag property.
     * 
     */
    public void setE038ExclusionValidationEnableFlag(boolean value) {
        this.e038ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e039ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE039ExclusionValidationEnableFlag() {
        return e039ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e039ExclusionValidationEnableFlag property.
     * 
     */
    public void setE039ExclusionValidationEnableFlag(boolean value) {
        this.e039ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e040ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE040ExclusionValidationEnableFlag() {
        return e040ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e040ExclusionValidationEnableFlag property.
     * 
     */
    public void setE040ExclusionValidationEnableFlag(boolean value) {
        this.e040ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e041ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE041ExclusionValidationEnableFlag() {
        return e041ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e041ExclusionValidationEnableFlag property.
     * 
     */
    public void setE041ExclusionValidationEnableFlag(boolean value) {
        this.e041ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e042ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE042ExclusionValidationEnableFlag() {
        return e042ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e042ExclusionValidationEnableFlag property.
     * 
     */
    public void setE042ExclusionValidationEnableFlag(boolean value) {
        this.e042ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the e043ExclusionValidationEnableFlag property.
     * 
     */
    public boolean isE043ExclusionValidationEnableFlag() {
        return e043ExclusionValidationEnableFlag;
    }

    /**
     * Sets the value of the e043ExclusionValidationEnableFlag property.
     * 
     */
    public void setE043ExclusionValidationEnableFlag(boolean value) {
        this.e043ExclusionValidationEnableFlag = value;
    }

    /**
     * Gets the value of the headerRuleExclusionsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headerRuleExclusionsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaderRuleExclusionsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorExclusionWebServiceVO }
     * 
     * 
     */
    public List<ErrorExclusionWebServiceVO> getHeaderRuleExclusionsList() {
        if (headerRuleExclusionsList == null) {
            headerRuleExclusionsList = new ArrayList<ErrorExclusionWebServiceVO>();
        }
        return this.headerRuleExclusionsList;
    }

    /**
     * Gets the value of the spsExclusionsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spsExclusionsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpsExclusionsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorExclusionWebServiceVO }
     * 
     * 
     */
    public List<ErrorExclusionWebServiceVO> getSpsExclusionsList() {
        if (spsExclusionsList == null) {
            spsExclusionsList = new ArrayList<ErrorExclusionWebServiceVO>();
        }
        return this.spsExclusionsList;
    }

    /**
     * Gets the value of the variableExclusionsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variableExclusionsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariableExclusionsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorExclusionWebServiceVO }
     * 
     * 
     */
    public List<ErrorExclusionWebServiceVO> getVariableExclusionsList() {
        if (variableExclusionsList == null) {
            variableExclusionsList = new ArrayList<ErrorExclusionWebServiceVO>();
        }
        return this.variableExclusionsList;
    }

}
