//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hippaSegmentWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hippaSegmentWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hippaCodePossibleValuesForEwpd" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaCodeValueWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hippaCodePossibleValuesForLgIsg" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hippaCodeSelectedValuesForEwpd" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}hippaCodeValueWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hippaCodeSelectedValuesForLgIsg" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hippaSegmentDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hippaSegmentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eb03Association" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}eb03AssociationWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hippaSegmentWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "description",
    "hippaCodePossibleValuesForEwpd",
    "hippaCodePossibleValuesForLgIsg",
    "hippaCodeSelectedValuesForEwpd",
    "hippaCodeSelectedValuesForLgIsg",
    "hippaSegmentDefinition",
    "hippaSegmentName",
    "name",
    "eb03Association"
})
public class HippaSegmentWebServiceVO {

    protected String description;
    @XmlElement(nillable = true)
    protected List<HippaCodeValueWebServiceVO> hippaCodePossibleValuesForEwpd;
    @XmlElement(nillable = true)
    protected List<String> hippaCodePossibleValuesForLgIsg;
    @XmlElement(nillable = true)
    protected List<HippaCodeValueWebServiceVO> hippaCodeSelectedValuesForEwpd;
    @XmlElement(nillable = true)
    protected List<String> hippaCodeSelectedValuesForLgIsg;
    protected String hippaSegmentDefinition;
    protected String hippaSegmentName;
    protected String name;
    @XmlElement(nillable = true)
    protected List<Eb03AssociationWebServiceVO> eb03Association;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the hippaCodePossibleValuesForEwpd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hippaCodePossibleValuesForEwpd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHippaCodePossibleValuesForEwpd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HippaCodeValueWebServiceVO }
     * 
     * 
     */
    public List<HippaCodeValueWebServiceVO> getHippaCodePossibleValuesForEwpd() {
        if (hippaCodePossibleValuesForEwpd == null) {
            hippaCodePossibleValuesForEwpd = new ArrayList<HippaCodeValueWebServiceVO>();
        }
        return this.hippaCodePossibleValuesForEwpd;
    }

    /**
     * Gets the value of the hippaCodePossibleValuesForLgIsg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hippaCodePossibleValuesForLgIsg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHippaCodePossibleValuesForLgIsg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHippaCodePossibleValuesForLgIsg() {
        if (hippaCodePossibleValuesForLgIsg == null) {
            hippaCodePossibleValuesForLgIsg = new ArrayList<String>();
        }
        return this.hippaCodePossibleValuesForLgIsg;
    }

    /**
     * Gets the value of the hippaCodeSelectedValuesForEwpd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hippaCodeSelectedValuesForEwpd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHippaCodeSelectedValuesForEwpd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HippaCodeValueWebServiceVO }
     * 
     * 
     */
    public List<HippaCodeValueWebServiceVO> getHippaCodeSelectedValuesForEwpd() {
        if (hippaCodeSelectedValuesForEwpd == null) {
            hippaCodeSelectedValuesForEwpd = new ArrayList<HippaCodeValueWebServiceVO>();
        }
        return this.hippaCodeSelectedValuesForEwpd;
    }

    /**
     * Gets the value of the hippaCodeSelectedValuesForLgIsg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hippaCodeSelectedValuesForLgIsg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHippaCodeSelectedValuesForLgIsg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHippaCodeSelectedValuesForLgIsg() {
        if (hippaCodeSelectedValuesForLgIsg == null) {
            hippaCodeSelectedValuesForLgIsg = new ArrayList<String>();
        }
        return this.hippaCodeSelectedValuesForLgIsg;
    }

    /**
     * Gets the value of the hippaSegmentDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHippaSegmentDefinition() {
        return hippaSegmentDefinition;
    }

    /**
     * Sets the value of the hippaSegmentDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHippaSegmentDefinition(String value) {
        this.hippaSegmentDefinition = value;
    }

    /**
     * Gets the value of the hippaSegmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHippaSegmentName() {
        return hippaSegmentName;
    }

    /**
     * Sets the value of the hippaSegmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHippaSegmentName(String value) {
        this.hippaSegmentName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the eb03Association property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eb03Association property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEb03Association().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Eb03AssociationWebServiceVO }
     * 
     * 
     */
    public List<Eb03AssociationWebServiceVO> getEb03Association() {
        if (eb03Association == null) {
            eb03Association = new ArrayList<Eb03AssociationWebServiceVO>();
        }
        return this.eb03Association;
    }

}
