//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hippaSegmentMappingWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hippaSegmentMappingWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eb01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eb02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eb03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eb06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eb09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hsd08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ii02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="messageTypeRequired" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="noteTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sensitiveBenefitIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="utilizationMgmntRule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableMappingStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hippaSegmentMappingWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "accum",
    "eb01",
    "eb02",
    "eb03",
    "eb06",
    "eb09",
    "hsd01",
    "hsd02",
    "hsd03",
    "hsd04",
    "hsd05",
    "hsd06",
    "hsd07",
    "hsd08",
    "ii02",
    "message",
    "messageTypeRequired",
    "noteTypeCode",
    "sensitiveBenefitIndicator",
    "utilizationMgmntRule",
    "variableMappingStatus"
})
public class HippaSegmentMappingWebServiceVO {

    protected String accum;
    protected String eb01;
    protected String eb02;
    protected String eb03;
    protected String eb06;
    protected String eb09;
    protected String hsd01;
    protected String hsd02;
    protected String hsd03;
    protected String hsd04;
    protected String hsd05;
    protected String hsd06;
    protected String hsd07;
    protected String hsd08;
    protected String ii02;
    protected String message;
    protected String messageTypeRequired;
    protected String noteTypeCode;
    protected String sensitiveBenefitIndicator;
    protected String utilizationMgmntRule;
    protected String variableMappingStatus;

    /**
     * Gets the value of the accum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccum() {
        return accum;
    }

    /**
     * Sets the value of the accum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccum(String value) {
        this.accum = value;
    }

    /**
     * Gets the value of the eb01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEb01() {
        return eb01;
    }

    /**
     * Sets the value of the eb01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEb01(String value) {
        this.eb01 = value;
    }

    /**
     * Gets the value of the eb02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEb02() {
        return eb02;
    }

    /**
     * Sets the value of the eb02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEb02(String value) {
        this.eb02 = value;
    }

    /**
     * Gets the value of the eb03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEb03() {
        return eb03;
    }

    /**
     * Sets the value of the eb03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEb03(String value) {
        this.eb03 = value;
    }

    /**
     * Gets the value of the eb06 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEb06() {
        return eb06;
    }

    /**
     * Sets the value of the eb06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEb06(String value) {
        this.eb06 = value;
    }

    /**
     * Gets the value of the eb09 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEb09() {
        return eb09;
    }

    /**
     * Sets the value of the eb09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEb09(String value) {
        this.eb09 = value;
    }

    /**
     * Gets the value of the hsd01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd01() {
        return hsd01;
    }

    /**
     * Sets the value of the hsd01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd01(String value) {
        this.hsd01 = value;
    }

    /**
     * Gets the value of the hsd02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd02() {
        return hsd02;
    }

    /**
     * Sets the value of the hsd02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd02(String value) {
        this.hsd02 = value;
    }

    /**
     * Gets the value of the hsd03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd03() {
        return hsd03;
    }

    /**
     * Sets the value of the hsd03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd03(String value) {
        this.hsd03 = value;
    }

    /**
     * Gets the value of the hsd04 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd04() {
        return hsd04;
    }

    /**
     * Sets the value of the hsd04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd04(String value) {
        this.hsd04 = value;
    }

    /**
     * Gets the value of the hsd05 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd05() {
        return hsd05;
    }

    /**
     * Sets the value of the hsd05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd05(String value) {
        this.hsd05 = value;
    }

    /**
     * Gets the value of the hsd06 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd06() {
        return hsd06;
    }

    /**
     * Sets the value of the hsd06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd06(String value) {
        this.hsd06 = value;
    }

    /**
     * Gets the value of the hsd07 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd07() {
        return hsd07;
    }

    /**
     * Sets the value of the hsd07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd07(String value) {
        this.hsd07 = value;
    }

    /**
     * Gets the value of the hsd08 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsd08() {
        return hsd08;
    }

    /**
     * Sets the value of the hsd08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsd08(String value) {
        this.hsd08 = value;
    }

    /**
     * Gets the value of the ii02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIi02() {
        return ii02;
    }

    /**
     * Sets the value of the ii02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIi02(String value) {
        this.ii02 = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the messageTypeRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageTypeRequired() {
        return messageTypeRequired;
    }

    /**
     * Sets the value of the messageTypeRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageTypeRequired(String value) {
        this.messageTypeRequired = value;
    }

    /**
     * Gets the value of the noteTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteTypeCode() {
        return noteTypeCode;
    }

    /**
     * Sets the value of the noteTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteTypeCode(String value) {
        this.noteTypeCode = value;
    }

    /**
     * Gets the value of the sensitiveBenefitIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensitiveBenefitIndicator() {
        return sensitiveBenefitIndicator;
    }

    /**
     * Sets the value of the sensitiveBenefitIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensitiveBenefitIndicator(String value) {
        this.sensitiveBenefitIndicator = value;
    }

    /**
     * Gets the value of the utilizationMgmntRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtilizationMgmntRule() {
        return utilizationMgmntRule;
    }

    /**
     * Sets the value of the utilizationMgmntRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtilizationMgmntRule(String value) {
        this.utilizationMgmntRule = value;
    }

    /**
     * Gets the value of the variableMappingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableMappingStatus() {
        return variableMappingStatus;
    }

    /**
     * Sets the value of the variableMappingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableMappingStatus(String value) {
        this.variableMappingStatus = value;
    }

}
