//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for minorHeadingsWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="minorHeadingsWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adminMethodSPS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="descriptionText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorCodesList" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}errorDetailWebServiceVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="flagBenefitCovered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="flagBenefitCoveredNpar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="flagBenefitCoveredPar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mappings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="value" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}contractMappingWebServiceVO" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ruleMapping" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}contractMappingWebServiceVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "minorHeadingsWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "adminMethodSPS",
    "descriptionText",
    "errorCodesList",
    "flagBenefitCovered",
    "flagBenefitCoveredNpar",
    "flagBenefitCoveredPar",
    "mappings",
    "ruleMapping"
})
public class MinorHeadingsWebServiceVO {

    @XmlElement(required = true)
    protected MinorHeadingsWebServiceVO.AdminMethodSPS adminMethodSPS;
    protected String descriptionText;
    @XmlElement(nillable = true)
    protected List<ErrorDetailWebServiceVO> errorCodesList;
    protected boolean flagBenefitCovered;
    protected boolean flagBenefitCoveredNpar;
    protected boolean flagBenefitCoveredPar;
    @XmlElement(required = true)
    protected MinorHeadingsWebServiceVO.Mappings mappings;
    protected ContractMappingWebServiceVO ruleMapping;

    /**
     * Gets the value of the adminMethodSPS property.
     * 
     * @return
     *     possible object is
     *     {@link MinorHeadingsWebServiceVO.AdminMethodSPS }
     *     
     */
    public MinorHeadingsWebServiceVO.AdminMethodSPS getAdminMethodSPS() {
        return adminMethodSPS;
    }

    /**
     * Sets the value of the adminMethodSPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinorHeadingsWebServiceVO.AdminMethodSPS }
     *     
     */
    public void setAdminMethodSPS(MinorHeadingsWebServiceVO.AdminMethodSPS value) {
        this.adminMethodSPS = value;
    }

    /**
     * Gets the value of the descriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionText() {
        return descriptionText;
    }

    /**
     * Sets the value of the descriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionText(String value) {
        this.descriptionText = value;
    }

    /**
     * Gets the value of the errorCodesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorCodesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorCodesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorDetailWebServiceVO }
     * 
     * 
     */
    public List<ErrorDetailWebServiceVO> getErrorCodesList() {
        if (errorCodesList == null) {
            errorCodesList = new ArrayList<ErrorDetailWebServiceVO>();
        }
        return this.errorCodesList;
    }

    /**
     * Gets the value of the flagBenefitCovered property.
     * 
     */
    public boolean isFlagBenefitCovered() {
        return flagBenefitCovered;
    }

    /**
     * Sets the value of the flagBenefitCovered property.
     * 
     */
    public void setFlagBenefitCovered(boolean value) {
        this.flagBenefitCovered = value;
    }

    /**
     * Gets the value of the flagBenefitCoveredNpar property.
     * 
     */
    public boolean isFlagBenefitCoveredNpar() {
        return flagBenefitCoveredNpar;
    }

    /**
     * Sets the value of the flagBenefitCoveredNpar property.
     * 
     */
    public void setFlagBenefitCoveredNpar(boolean value) {
        this.flagBenefitCoveredNpar = value;
    }

    /**
     * Gets the value of the flagBenefitCoveredPar property.
     * 
     */
    public boolean isFlagBenefitCoveredPar() {
        return flagBenefitCoveredPar;
    }

    /**
     * Sets the value of the flagBenefitCoveredPar property.
     * 
     */
    public void setFlagBenefitCoveredPar(boolean value) {
        this.flagBenefitCoveredPar = value;
    }

    /**
     * Gets the value of the mappings property.
     * 
     * @return
     *     possible object is
     *     {@link MinorHeadingsWebServiceVO.Mappings }
     *     
     */
    public MinorHeadingsWebServiceVO.Mappings getMappings() {
        return mappings;
    }

    /**
     * Sets the value of the mappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinorHeadingsWebServiceVO.Mappings }
     *     
     */
    public void setMappings(MinorHeadingsWebServiceVO.Mappings value) {
        this.mappings = value;
    }

    /**
     * Gets the value of the ruleMapping property.
     * 
     * @return
     *     possible object is
     *     {@link ContractMappingWebServiceVO }
     *     
     */
    public ContractMappingWebServiceVO getRuleMapping() {
        return ruleMapping;
    }

    /**
     * Sets the value of the ruleMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractMappingWebServiceVO }
     *     
     */
    public void setRuleMapping(ContractMappingWebServiceVO value) {
        this.ruleMapping = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class AdminMethodSPS {

        protected List<MinorHeadingsWebServiceVO.AdminMethodSPS.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MinorHeadingsWebServiceVO.AdminMethodSPS.Entry }
         * 
         * 
         */
        public List<MinorHeadingsWebServiceVO.AdminMethodSPS.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<MinorHeadingsWebServiceVO.AdminMethodSPS.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry {

            protected String key;
            protected String value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="value" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}contractMappingWebServiceVO" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class Mappings {

        protected List<MinorHeadingsWebServiceVO.Mappings.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MinorHeadingsWebServiceVO.Mappings.Entry }
         * 
         * 
         */
        public List<MinorHeadingsWebServiceVO.Mappings.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<MinorHeadingsWebServiceVO.Mappings.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="value" type="{http://impl.webservices.simulation.ebx.ets.wellpoint.com/}contractMappingWebServiceVO" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry {

            protected String key;
            protected ContractMappingWebServiceVO value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link ContractMappingWebServiceVO }
             *     
             */
            public ContractMappingWebServiceVO getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link ContractMappingWebServiceVO }
             *     
             */
            public void setValue(ContractMappingWebServiceVO value) {
                this.value = value;
            }

        }

    }

}
