//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wellpoint.ets.ebx.simulation.webservices.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetContractInfo_QNAME = new QName("http://impl.webservices.simulation.ebx.ets.wellpoint.com/", "getContractInfo");
    private final static QName _GetContractInfoResponse_QNAME = new QName("http://impl.webservices.simulation.ebx.ets.wellpoint.com/", "getContractInfoResponse");
    private final static QName _SimulationWebServiceException_QNAME = new QName("http://impl.webservices.simulation.ebx.ets.wellpoint.com/", "SimulationWebServiceException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wellpoint.ets.ebx.simulation.webservices.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MinorHeadingsWebServiceVO }
     * 
     */
    public MinorHeadingsWebServiceVO createMinorHeadingsWebServiceVO() {
        return new MinorHeadingsWebServiceVO();
    }

    /**
     * Create an instance of {@link VariableWebServiceVO }
     * 
     */
    public VariableWebServiceVO createVariableWebServiceVO() {
        return new VariableWebServiceVO();
    }

    /**
     * Create an instance of {@link MinorHeadingsWebServiceVO.Mappings }
     * 
     */
    public MinorHeadingsWebServiceVO.Mappings createMinorHeadingsWebServiceVOMappings() {
        return new MinorHeadingsWebServiceVO.Mappings();
    }

    /**
     * Create an instance of {@link SpsIdWebServiceVO }
     * 
     */
    public SpsIdWebServiceVO createSpsIdWebServiceVO() {
        return new SpsIdWebServiceVO();
    }

    /**
     * Create an instance of {@link MajorHeadingsWebServiceVO.MinorHeadings }
     * 
     */
    public MajorHeadingsWebServiceVO.MinorHeadings createMajorHeadingsWebServiceVOMinorHeadings() {
        return new MajorHeadingsWebServiceVO.MinorHeadings();
    }

    /**
     * Create an instance of {@link MajorHeadingsWebServiceVO }
     * 
     */
    public MajorHeadingsWebServiceVO createMajorHeadingsWebServiceVO() {
        return new MajorHeadingsWebServiceVO();
    }

    /**
     * Create an instance of {@link MappingWebServiceVO }
     * 
     */
    public MappingWebServiceVO createMappingWebServiceVO() {
        return new MappingWebServiceVO();
    }

    /**
     * Create an instance of {@link HippaSegmentWebServiceVO }
     * 
     */
    public HippaSegmentWebServiceVO createHippaSegmentWebServiceVO() {
        return new HippaSegmentWebServiceVO();
    }

    /**
     * Create an instance of {@link HippaCodeValueWebServiceVO }
     * 
     */
    public HippaCodeValueWebServiceVO createHippaCodeValueWebServiceVO() {
        return new HippaCodeValueWebServiceVO();
    }

    /**
     * Create an instance of {@link GetContractInfo }
     * 
     */
    public GetContractInfo createGetContractInfo() {
        return new GetContractInfo();
    }

    /**
     * Create an instance of {@link ContractMappingWebServiceVO }
     * 
     */
    public ContractMappingWebServiceVO createContractMappingWebServiceVO() {
        return new ContractMappingWebServiceVO();
    }

    /**
     * Create an instance of {@link MinorHeadingsWebServiceVO.Mappings.Entry }
     * 
     */
    public MinorHeadingsWebServiceVO.Mappings.Entry createMinorHeadingsWebServiceVOMappingsEntry() {
        return new MinorHeadingsWebServiceVO.Mappings.Entry();
    }

    /**
     * Create an instance of {@link UserWebServiceVO }
     * 
     */
    public UserWebServiceVO createUserWebServiceVO() {
        return new UserWebServiceVO();
    }

    /**
     * Create an instance of {@link ContractWebServiceVO.MajorHeadings }
     * 
     */
    public ContractWebServiceVO.MajorHeadings createContractWebServiceVOMajorHeadings() {
        return new ContractWebServiceVO.MajorHeadings();
    }

    /**
     * Create an instance of {@link MinorHeadingsWebServiceVO.AdminMethodSPS }
     * 
     */
    public MinorHeadingsWebServiceVO.AdminMethodSPS createMinorHeadingsWebServiceVOAdminMethodSPS() {
        return new MinorHeadingsWebServiceVO.AdminMethodSPS();
    }

    /**
     * Create an instance of {@link HippaSegmentMappingWebServiceVO }
     * 
     */
    public HippaSegmentMappingWebServiceVO createHippaSegmentMappingWebServiceVO() {
        return new HippaSegmentMappingWebServiceVO();
    }

    /**
     * Create an instance of {@link RuleWebServiceVO }
     * 
     */
    public RuleWebServiceVO createRuleWebServiceVO() {
        return new RuleWebServiceVO();
    }

    /**
     * Create an instance of {@link ErrorExclusionWebServiceVO }
     * 
     */
    public ErrorExclusionWebServiceVO createErrorExclusionWebServiceVO() {
        return new ErrorExclusionWebServiceVO();
    }

    /**
     * Create an instance of {@link ContractWebServiceVO.MajorHeadings.Entry }
     * 
     */
    public ContractWebServiceVO.MajorHeadings.Entry createContractWebServiceVOMajorHeadingsEntry() {
        return new ContractWebServiceVO.MajorHeadings.Entry();
    }

    /**
     * Create an instance of {@link ContractWebServiceVO }
     * 
     */
    public ContractWebServiceVO createContractWebServiceVO() {
        return new ContractWebServiceVO();
    }

    /**
     * Create an instance of {@link AuditTrailWebServiceVO }
     * 
     */
    public AuditTrailWebServiceVO createAuditTrailWebServiceVO() {
        return new AuditTrailWebServiceVO();
    }

    /**
     * Create an instance of {@link MinorHeadingsWebServiceVO.AdminMethodSPS.Entry }
     * 
     */
    public MinorHeadingsWebServiceVO.AdminMethodSPS.Entry createMinorHeadingsWebServiceVOAdminMethodSPSEntry() {
        return new MinorHeadingsWebServiceVO.AdminMethodSPS.Entry();
    }

    /**
     * Create an instance of {@link GetContractInfoResponse }
     * 
     */
    public GetContractInfoResponse createGetContractInfoResponse() {
        return new GetContractInfoResponse();
    }

    /**
     * Create an instance of {@link SimulationWebServiceException }
     * 
     */
    public SimulationWebServiceException createSimulationWebServiceException() {
        return new SimulationWebServiceException();
    }

    /**
     * Create an instance of {@link ErrorExclusionDetailWebServiceVO }
     * 
     */
    public ErrorExclusionDetailWebServiceVO createErrorExclusionDetailWebServiceVO() {
        return new ErrorExclusionDetailWebServiceVO();
    }

    /**
     * Create an instance of {@link MajorHeadingsWebServiceVO.MinorHeadings.Entry }
     * 
     */
    public MajorHeadingsWebServiceVO.MinorHeadings.Entry createMajorHeadingsWebServiceVOMinorHeadingsEntry() {
        return new MajorHeadingsWebServiceVO.MinorHeadings.Entry();
    }

    /**
     * Create an instance of {@link ErrorDetailWebServiceVO }
     * 
     */
    public ErrorDetailWebServiceVO createErrorDetailWebServiceVO() {
        return new ErrorDetailWebServiceVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContractInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", name = "getContractInfo")
    public JAXBElement<GetContractInfo> createGetContractInfo(GetContractInfo value) {
        return new JAXBElement<GetContractInfo>(_GetContractInfo_QNAME, GetContractInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContractInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", name = "getContractInfoResponse")
    public JAXBElement<GetContractInfoResponse> createGetContractInfoResponse(GetContractInfoResponse value) {
        return new JAXBElement<GetContractInfoResponse>(_GetContractInfoResponse_QNAME, GetContractInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimulationWebServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", name = "SimulationWebServiceException")
    public JAXBElement<SimulationWebServiceException> createSimulationWebServiceException(SimulationWebServiceException value) {
        return new JAXBElement<SimulationWebServiceException>(_SimulationWebServiceException_QNAME, SimulationWebServiceException.class, null, value);
    }

}
