//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/")
package com.wellpoint.ets.ebx.simulation.webservices.client;
