//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for spsIdWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="spsIdWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="levelDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineDataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linePVA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spsDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spsDetail" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="spsId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spsType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spsIdWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "levelDesc",
    "lineDataType",
    "linePVA",
    "lineValue",
    "spsDesc",
    "spsDetail",
    "spsId",
    "spsType"
})
public class SpsIdWebServiceVO {

    protected String levelDesc;
    protected String lineDataType;
    protected String linePVA;
    protected String lineValue;
    protected String spsDesc;
    @XmlElement(nillable = true)
    protected List<String> spsDetail;
    protected String spsId;
    protected String spsType;

    /**
     * Gets the value of the levelDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelDesc() {
        return levelDesc;
    }

    /**
     * Sets the value of the levelDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelDesc(String value) {
        this.levelDesc = value;
    }

    /**
     * Gets the value of the lineDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineDataType() {
        return lineDataType;
    }

    /**
     * Sets the value of the lineDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineDataType(String value) {
        this.lineDataType = value;
    }

    /**
     * Gets the value of the linePVA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinePVA() {
        return linePVA;
    }

    /**
     * Sets the value of the linePVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinePVA(String value) {
        this.linePVA = value;
    }

    /**
     * Gets the value of the lineValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineValue() {
        return lineValue;
    }

    /**
     * Sets the value of the lineValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineValue(String value) {
        this.lineValue = value;
    }

    /**
     * Gets the value of the spsDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpsDesc() {
        return spsDesc;
    }

    /**
     * Sets the value of the spsDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpsDesc(String value) {
        this.spsDesc = value;
    }

    /**
     * Gets the value of the spsDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spsDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpsDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpsDetail() {
        if (spsDetail == null) {
            spsDetail = new ArrayList<String>();
        }
        return this.spsDetail;
    }

    /**
     * Gets the value of the spsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpsId() {
        return spsId;
    }

    /**
     * Sets the value of the spsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpsId(String value) {
        this.spsId = value;
    }

    /**
     * Gets the value of the spsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpsType() {
        return spsType;
    }

    /**
     * Sets the value of the spsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpsType(String value) {
        this.spsType = value;
    }

}
