//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.wellpoint.ets.ebx.simulation.webservices.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for variableWebServiceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="variableWebServiceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="auditLock" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="codedStatus" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="createdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isAdvanceSearch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isgCatagory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lgCatagory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="majorHeadings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mappedVariable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mappingRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="minorHeadings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notApplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="pva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sensitiveBenefitIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unmappedVariable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="variableDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variableValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "variableWebServiceVO", namespace = "http://impl.webservices.simulation.ebx.ets.wellpoint.com/", propOrder = {
    "auditLock",
    "codedStatus",
    "createdDate",
    "dataType",
    "description",
    "isAdvanceSearch",
    "isgCatagory",
    "lgCatagory",
    "majorHeadings",
    "mappedVariable",
    "mappingRequired",
    "message",
    "minorHeadings",
    "notApplicable",
    "pva",
    "sensitiveBenefitIndicator",
    "unmappedVariable",
    "variableDescription",
    "variableFormat",
    "variableId",
    "variableStatus",
    "variableSystem",
    "variableValue"
})
public class VariableWebServiceVO {

    protected boolean auditLock;
    protected boolean codedStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    protected String dataType;
    protected String description;
    protected String isAdvanceSearch;
    protected String isgCatagory;
    protected String lgCatagory;
    protected String majorHeadings;
    protected boolean mappedVariable;
    protected boolean mappingRequired;
    protected String message;
    protected String minorHeadings;
    protected boolean notApplicable;
    protected String pva;
    protected String sensitiveBenefitIndicator;
    protected boolean unmappedVariable;
    protected String variableDescription;
    protected String variableFormat;
    protected String variableId;
    protected String variableStatus;
    protected String variableSystem;
    protected String variableValue;

    /**
     * Gets the value of the auditLock property.
     * 
     */
    public boolean isAuditLock() {
        return auditLock;
    }

    /**
     * Sets the value of the auditLock property.
     * 
     */
    public void setAuditLock(boolean value) {
        this.auditLock = value;
    }

    /**
     * Gets the value of the codedStatus property.
     * 
     */
    public boolean isCodedStatus() {
        return codedStatus;
    }

    /**
     * Sets the value of the codedStatus property.
     * 
     */
    public void setCodedStatus(boolean value) {
        this.codedStatus = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the isAdvanceSearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAdvanceSearch() {
        return isAdvanceSearch;
    }

    /**
     * Sets the value of the isAdvanceSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsAdvanceSearch(String value) {
        this.isAdvanceSearch = value;
    }

    /**
     * Gets the value of the isgCatagory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsgCatagory() {
        return isgCatagory;
    }

    /**
     * Sets the value of the isgCatagory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsgCatagory(String value) {
        this.isgCatagory = value;
    }

    /**
     * Gets the value of the lgCatagory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLgCatagory() {
        return lgCatagory;
    }

    /**
     * Sets the value of the lgCatagory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLgCatagory(String value) {
        this.lgCatagory = value;
    }

    /**
     * Gets the value of the majorHeadings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorHeadings() {
        return majorHeadings;
    }

    /**
     * Sets the value of the majorHeadings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorHeadings(String value) {
        this.majorHeadings = value;
    }

    /**
     * Gets the value of the mappedVariable property.
     * 
     */
    public boolean isMappedVariable() {
        return mappedVariable;
    }

    /**
     * Sets the value of the mappedVariable property.
     * 
     */
    public void setMappedVariable(boolean value) {
        this.mappedVariable = value;
    }

    /**
     * Gets the value of the mappingRequired property.
     * 
     */
    public boolean isMappingRequired() {
        return mappingRequired;
    }

    /**
     * Sets the value of the mappingRequired property.
     * 
     */
    public void setMappingRequired(boolean value) {
        this.mappingRequired = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the minorHeadings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorHeadings() {
        return minorHeadings;
    }

    /**
     * Sets the value of the minorHeadings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorHeadings(String value) {
        this.minorHeadings = value;
    }

    /**
     * Gets the value of the notApplicable property.
     * 
     */
    public boolean isNotApplicable() {
        return notApplicable;
    }

    /**
     * Sets the value of the notApplicable property.
     * 
     */
    public void setNotApplicable(boolean value) {
        this.notApplicable = value;
    }

    /**
     * Gets the value of the pva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPva() {
        return pva;
    }

    /**
     * Sets the value of the pva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPva(String value) {
        this.pva = value;
    }

    /**
     * Gets the value of the sensitiveBenefitIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensitiveBenefitIndicator() {
        return sensitiveBenefitIndicator;
    }

    /**
     * Sets the value of the sensitiveBenefitIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensitiveBenefitIndicator(String value) {
        this.sensitiveBenefitIndicator = value;
    }

    /**
     * Gets the value of the unmappedVariable property.
     * 
     */
    public boolean isUnmappedVariable() {
        return unmappedVariable;
    }

    /**
     * Sets the value of the unmappedVariable property.
     * 
     */
    public void setUnmappedVariable(boolean value) {
        this.unmappedVariable = value;
    }

    /**
     * Gets the value of the variableDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableDescription() {
        return variableDescription;
    }

    /**
     * Sets the value of the variableDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableDescription(String value) {
        this.variableDescription = value;
    }

    /**
     * Gets the value of the variableFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableFormat() {
        return variableFormat;
    }

    /**
     * Sets the value of the variableFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableFormat(String value) {
        this.variableFormat = value;
    }

    /**
     * Gets the value of the variableId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableId() {
        return variableId;
    }

    /**
     * Sets the value of the variableId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableId(String value) {
        this.variableId = value;
    }

    /**
     * Gets the value of the variableStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableStatus() {
        return variableStatus;
    }

    /**
     * Sets the value of the variableStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableStatus(String value) {
        this.variableStatus = value;
    }

    /**
     * Gets the value of the variableSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableSystem() {
        return variableSystem;
    }

    /**
     * Sets the value of the variableSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableSystem(String value) {
        this.variableSystem = value;
    }

    /**
     * Gets the value of the variableValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableValue() {
        return variableValue;
    }

    /**
     * Sets the value of the variableValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableValue(String value) {
        this.variableValue = value;
    }

}
